SET DEFINE OFF

CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  email VARCHAR2(255) NOT NULL,
  hash_of_password VARCHAR2(255) NOT NULL,
  full_name VARCHAR2(255) NOT NULL,
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE currencies (
  currency_code VARCHAR2(10) PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  is_crypto NUMBER(1) NOT NULL,
  CONSTRAINT chk_currencies_is_crypto CHECK (is_crypto IN (0, 1))
);

CREATE TABLE trading_pairs (
  pair_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  base_currency_code VARCHAR2(10) NOT NULL,
  quote_currency_code VARCHAR2(10) NOT NULL,
  CONSTRAINT uq_trading_pairs_codes UNIQUE (base_currency_code, quote_currency_code),
  CONSTRAINT chk_trading_pairs_distinct CHECK (base_currency_code <> quote_currency_code),
  CONSTRAINT fk_trading_pairs_base FOREIGN KEY (base_currency_code) REFERENCES currencies(currency_code) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_trading_pairs_quote FOREIGN KEY (quote_currency_code) REFERENCES currencies(currency_code) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE wallets (
  wallet_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  currency_code VARCHAR2(10) NOT NULL,
  balance NUMBER(18,8) DEFAULT 0 NOT NULL,
  CONSTRAINT uq_wallets_user_currency UNIQUE (user_id, currency_code),
  CONSTRAINT chk_wallets_balance CHECK (balance >= 0),
  CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES users(user_id) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_wallets_currency FOREIGN KEY (currency_code) REFERENCES currencies(currency_code) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE exchange_transactions (
  transaction_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  pair_id NUMBER NOT NULL,
  from_currency_code VARCHAR2(10) NOT NULL,
  to_currency_code VARCHAR2(10) NOT NULL,
  from_amount NUMBER(18,8) NOT NULL,
  exchange_rate NUMBER(18,8) NOT NULL,
  to_amount NUMBER(18,8) NOT NULL,
  transaction_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status VARCHAR2(20) NOT NULL,
  CONSTRAINT chk_ex_tx_from_amount CHECK (from_amount > 0),
  CONSTRAINT chk_ex_tx_rate CHECK (exchange_rate > 0),
  CONSTRAINT chk_ex_tx_to_amount CHECK (to_amount > 0),
  CONSTRAINT chk_ex_tx_status CHECK (status IN ('DONE', 'FAILED', 'PENDING')),
  CONSTRAINT fk_ex_tx_user FOREIGN KEY (user_id) REFERENCES users(user_id) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_ex_tx_pair FOREIGN KEY (pair_id) REFERENCES trading_pairs(pair_id) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_ex_tx_from_currency FOREIGN KEY (from_currency_code) REFERENCES currencies(currency_code) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_ex_tx_to_currency FOREIGN KEY (to_currency_code) REFERENCES currencies(currency_code) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE wallet_operations (
  operation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  wallet_id NUMBER NOT NULL,
  transaction_id NUMBER NULL,
  operation_type VARCHAR2(20) NOT NULL,
  amount NUMBER(18,8) NOT NULL,
  operation_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_wallet_ops_amount CHECK (amount <> 0),
  CONSTRAINT chk_wallet_ops_type CHECK (operation_type IN (
    'FIAT_DEPOSIT', 'FIAT_WITHDRAWAL', 'CRYPTO_DEPOSIT', 'CRYPTO_WITHDRAWAL',
    'BUY_FIAT_OUT', 'BUY_CRYPTO_IN', 'SELL_CRYPTO_OUT', 'SELL_FIAT_IN'
  )),
  CONSTRAINT fk_wallet_ops_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_wallet_ops_transaction FOREIGN KEY (transaction_id) REFERENCES exchange_transactions(transaction_id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE exchange_rates (
  rate_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  pair_id NUMBER NOT NULL,
  rate NUMBER(18,8) NOT NULL,
  valid_from TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  valid_to TIMESTAMP NULL,
  CONSTRAINT uq_exchange_rates_pair_from UNIQUE (pair_id, valid_from),
  CONSTRAINT chk_exchange_rates_rate CHECK (rate > 0),
  CONSTRAINT chk_exchange_rates_interval CHECK (valid_to IS NULL OR valid_to > valid_from),
  CONSTRAINT fk_exchange_rates_pair FOREIGN KEY (pair_id) REFERENCES trading_pairs(pair_id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE UNIQUE INDEX ux_exchange_rates_current
  ON exchange_rates (CASE WHEN valid_to IS NULL THEN pair_id END);

CREATE INDEX ix_wallet_operations_wallet_time ON wallet_operations(wallet_id, operation_time);
CREATE INDEX ix_exchange_transactions_user_time ON exchange_transactions(user_id, transaction_time);
CREATE INDEX ix_exchange_rates_pair_time ON exchange_rates(pair_id, valid_from, valid_to);
